GET http://localhost:3000/api/hello

###
POST http://localhost:3000/api/chats
Content-Type: application/json

{
  "message": "Hello World 5 "
}

###
GET http://localhost:3000/api/chats

###
@chatId = b5b3c511-d745-4b20-831a-49f858144716
GET http://localhost:3000/api/chats/{{chatId}}/messages

###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json

{
  "message": "i'm testing the api"
}

###
@messageId = 944ed96e-724c-4aac-86e8-b84e50d98bd8
GET http://localhost:3000/api/messages/{{messageId}}/sse