version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - .docker/db/data:/var/lib/mysql
    ports:
      - "3308:3306"
